name: Release Workflow

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: registry.gitlab.aleph-alpha.de
  REPO_OWNER: research/public-registry
  IMAGE_NAME: eval_framework

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "~=0.8.16"

      - name: Check tag
        # For test releases, we allow any version
        if: github.event_name == 'release'
        shell: bash
        run: |
            PACKAGE_VERSION=$(uv version --short)
            RELEASE_VERSION=${GITHUB_REF#refs/*/}

            if [ "$RELEASE_VERSION" != "v$PACKAGE_VERSION" ];
            then
              echo "Tag '${RELEASE_VERSION}' does not match the package version '${PACKAGE_VERSION}'!";
              exit 1;
            fi

      - name: Build Wheel
        run: uv build --out-dir ./dist .

      - uses: actions/upload-artifact@v4
        with:
          name: 'pypi-dist'
          path: './dist'
          if-no-files-found: 'error'

  # Deploy to our pypi main instance
  deploy-pypi:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: ["build"]
    environment: pypi
    permissions:
      # This permission is mandatory for Trusted Publishing
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write

    steps:
      - name: Download dist
        uses: actions/download-artifact@v5
        with:
          name: 'pypi-dist'
          path: './dist'

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true
          print-hash: true

  # Deploy to our pypi test instance
  deploy-pypi-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: ["build"]
    environment: testpypi
    permissions:
      # This permission is mandatory for Trusted Publishing
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write

    steps:
      - name: Download dist
        uses: actions/download-artifact@v5
        with:
          name: 'pypi-dist'
          path: './dist'

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          # Test release platform for now
          repository-url: https://test.pypi.org/legacy/
          skip-existing: false
          print-hash: true

  # Deploy Docker images with version tags
  deploy-docker:
    if: github.event_name == 'release'
    runs-on: cpu-runner-8c-32gb-01
    container: docker:dind
    needs: ["deploy-pypi"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-2)

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "major_minor=$MAJOR_MINOR" >> $GITHUB_OUTPUT

      - name: Registry Authentication
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: token
          password: ${{ secrets.GL_PUBLIC_REGISTRY_READ_WRITE_TOKEN }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:v${{ steps.version.outputs.major_minor }}
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:v${{ steps.version.outputs.version }}
